version: '3.7'

services:
  hdfs:
    image: ${HDFS_IMAGE:-mtsrus/hadoop:hadoop2-hdfs}
    restart: no
    container_name: hdfs
    hostname: hdfs
    ports:
    - 9820:9820  # HDFS IPC
    - 9870:9870  # HDFS WebHDFS
    volumes:
      # put some .xml files in /var/hadoop/conf/ to override defaults
    - ./conf/hadoop/:/var/hadoop/conf/
    - hadoop-data:/var/hadoop/data/

volumes:
  hadoop-data:
