version: '3.7'

services:
  yarn:
    image: ${YARN_IMAGE:-mtsrus/hadoop:hadoop2-yarn}
    restart: unless-stopped
    container_name: yarn
    hostname: yarn
    environment:
    - WITH_MAPREDUCE=true
    ports:
    - 8025:8025  # ResourceManager http
    - 8030:8030  # Scheduler
    - 8042:8042  # NodeManager UI
    - 8050:8050  # ResourceManager IPC
    - 8088:8088  # Yarn UI
    - 8188:8188 # Timeline server
    - 9820:9820  # HDFS IPC
    - 9870:9870  # WebHDFS
    - 9864:9864  # Datanode UI
    - 9867:9867  # Datanode IPC
    - 10020:10020 # MapReduce JobServer
    - 19888:19888 # MapReduce JobServer History
    volumes:
      # put some .xml files in /var/hadoop/conf/ to override defaults
    - ./conf/hadoop/:/var/hadoop/conf/
    - hadoop-data:/var/hadoop/data/

volumes:
  hadoop-data:
